# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaptive_test_stat <- function(X, Y, sigma_sq, x_vals, h_vals, k) {
    .Call(`_MonotonicityTest_adaptive_test_stat`, X, Y, sigma_sq, x_vals, h_vals, k)
}

perform_adaptive_test <- function(X, Y, x_grid, h_grid, k) {
    .Call(`_MonotonicityTest_perform_adaptive_test`, X, Y, x_grid, h_grid, k)
}

get_hall_stat <- function(x, y, m) {
    .Call(`_MonotonicityTest_get_hall_stat`, x, y, m)
}

